### ISSUE TITLE
Implement variable paging for named slots

### ISSUE THREAD

**Issue by wk-j** [wk-j/github-detail-comment#6]
Currently variable paging is only implemented for indexed slots. Named slots are not paged at all.

I propose to implement variable paging for namedVariables as follows:
- keys are shown without square brackets.
- ranges are shown in the same way as for 'indexedVariables': [0..99]

Example:

```
o:
  [0..99]
    foo: "bar"
    xyz: 123
    abc: true
```
